### ISSUE TITLE
What are the stop-light yellow icons for?

### ISSUE THREAD

**Issue by gabrielflorit** [zlsa/indoc#12]
Not that I mind, but I'm not sure what they're for.
![screen shot 2016-09-02 at 6 44 38 pm](https://cloud.githubusercontent.com/assets/370976/18220154/59093f9a-713d-11e6-9157-3ef368aab2c7.png)

**Comment by zlsa** [comment]
They show the language the file is written in using GitHub's language colors (see https://github.com/ozh/github-colors). JS is yellow.
