### ISSUE TITLE
Is there a way to hide comments that start with a specific string?

### ISSUE THREAD

**Issue by gabrielflorit** [zlsa/indoc#13]
I'm specifically thinking of hiding `eslint-disable` declarations:

``` js
// eslint-disable global-require
import css from './../common/styles/config.styl'
```

**Comment by zlsa** [comment]
Not at the moment, but it should be an easy feature to add. I'll see what I can do.

**Comment by gabrielflorit** [comment]
Nice, looking forward to it. BTW `indoc` is making it easier for other devs to get up to speed on projects here at the Boston Globe (e.g. https://bostonglobe.github.io/elections-2016/) - so thank you very much!

**Comment by zlsa** [comment]
To add ignore strings, add the key `languages` in your config file (or the `options` object):

``` js
"name": "Indoc demo",
...
"languages": {
  "JavaScript": {
    "ignore": ["eslint-disable"]
  }
},
...
```

This feature is live in `0.4.12`.

**Comment by gabrielflorit** [comment]
very nice!
