### ISSUE TITLE
Long lines break layout

### ISSUE THREAD

**Issue by gabrielflorit** [zlsa/indoc#14]
Example: 
![screen shot 2017-02-02 at 5 54 58 pm](https://cloud.githubusercontent.com/assets/370976/22572157/cca1ec1c-e970-11e6-8aaa-cd5298dfd79e.png)

(comes from https://bostonglobe.github.io/snow/Makefile/)

**Comment by gabrielflorit** [comment]
wow that was quick!

**Comment by gabrielflorit** [comment]
FYI I still see it broken - but it works fine when I do `word-break: break-all`.

**Comment by zlsa** [comment]
What browser? I'm using Chrome 55 on Linux, and long lines are wrapping properly. I've added your fix though, and it's in `0.4.15`.

**Comment by gabrielflorit** [comment]
Chrome 55 on Mac. But `0.4.15` fixes it, thank you.
