### ISSUE TITLE
Multi line comments ( javascript )

### ISSUE THREAD

**Issue by lesterzone** [zlsa/indoc#9]
I have a big javascript project with comments like this:

``` js
/**
 * foobar
 * foobar foo
 *     foob
 *     bar
 */
```

I tried to use this configuration:

``` js
multi: [
  ['/**', '*', '*/']
]
```

But....it's not working? 
I'm missing something? Or.... this multi-line is not supported?

Thanks

**Comment by zlsa** [comment]
This has been fixed. The following should work (either in the `json` config file or in the `options` object):

``` json
...
"languages": {
  "JavaScript": {
    "extensions": ["js", "json"],
    "name": {
      "hljs": "JavaScript",
      "human": "JavaScript",
      "abbr": "js"
    },
    "single": [
      "//"
    ],
    "multi": [
      ["/**", "*", "*/"]
    ]
  },
},
...
```
